version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SERVER_PORT=8080
      - SERVER_TIMEOUT_READ=15s
      - SERVER_TIMEOUT_WRITE=15s
      - SERVER_HEALTH_CHECK_PORT=8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
